---

version: "3.8"

networks:
  test: {}

volumes:
  mongodata: {}
  mysqldata: {}

services:
  api:
    image: ${APP_NAME}:${APP_TAG}
    environment:
      MONGO_HOST: db
      MONGO_DB: invest
    expose:
      - 5000
    ports:
      - 5000:5000/tcp
    networks:
      - test
    depends_on:
      - db
  test:
    build: test
    environment:
      APP_HOST: api
      APP_PORT: 5000
    networks:
      - test
    depends_on:
      - api
  db:
    image: mongo:4
    expose:
      - 27017
    volumes:
      - mongodata:/var/lib/mongo
    networks:
      - test
  db-sql:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - test
  db-sql-setup:
    build: sql-setup
    environment:
      MYSQL_HOST: db-sql
      MYSQL_DB: test
      MYSQL_USER: root
      MYSQL_PASS: root
    networks:
      - test
    depends_on:
      - db-sql
