---

version: "3.8"

networks:
  test: {}

volumes:
  mongodata: {}

services:
  api:
    build: app
    environment:
      MONGO_HOST: db
      MONGO_DB: invest
    expose:
      - 5000
    ports:
      - 5000:5000/tcp
    networks:
      - test
    depends_on:
      - db
  test:
    build: test
    environment:
      APP_HOST: api
      APP_PORT: 5000
    networks:
      - test
    depends_on:
      - api
  db:
    image: mongo:4
    expose:
      - 27017
    volumes:
      - mongodata:/var/lib/mongo
    networks:
      - test
