name: Docker Image CI

on:
  pull_request:
    branches: [ devel ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build application
      run: make build
    - name: Start application
      run: make run
    - name: Test application
      run: make test
    - name: Clean
      run: make clean
    - name: automerge
      uses: "pascalgn/automerge-action@v0.13.0"
      env:
        GITHUB_TOKEN: "${{ secrets.GIT_TOKEN }}"
