name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start application
      run: make run
    - name: Scan image
      id: scan
      uses: anchore/scan-action@v2
      with:
        image: api-ci:${{ github.run_number }}
        fail-build: false
        severity-cutoff: critical
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image
      run: |
        docker tag api-ci:${{ github.run_number }} ${{ secrets.DOCKERHUB_USERNAME }}/api-ci:${{ github.run_number }}
        docker push luismiguelsaez/api-ci:${{ github.run_number }}
    - name: Clean
      run: make clean
